cosmetic

diff --git a/base/postgis/conf/dump_restore b/base/postgis/conf/dump_restore
--- a/base/postgis/conf/dump_restore
+++ b/base/postgis/conf/dump_restore
@@ -23,6 +23,7 @@ tag() {
 
 # create a new dump, while online
 dump() {
+
     # save app.jwt_secret and any other settings passed as an argument, to get
     # set again as part of the restore
     settings="
@@ -34,11 +35,10 @@ dump() {
     "
     for setting in app.jwt_secret "$@"; do
         value=$(pg.sh -Atc "select current_setting('$setting', true)")
-        settings="$settings
-            alter database $database set $setting to '$value';
-        "
+        settings+="alter database $database set $setting to '$value';"
     done
-    settings="$settings
+    settings+="
+        -- clean up after ourselves
         drop function __restore_settings;
         end \$body\$;
         commit;
@@ -48,25 +48,36 @@ dump() {
     # tag any existing dump files, so that we won't overwrite them
     tag
 
-    # save roles (which aren't included in pg_dump's backup file)
+    # save roles (they're not included in pg_dump's backup file)
     pg_dumpall -U "$POSTGRES_USER" --roles-only >"$roles"
 
     # backup database
     # https://postgis.net/docs/manual-dev/postgis_administration.html#hard_upgrade
     pg_dump -U "$POSTGRES_USER" -Fc -b -v -f "$backup" "$database"
+
+    # we don't need this in the database anymore; it just needed to be included
+    # in the dump
+    psql -U "$POSTGRES_USER" -c "
+        start transaction read write;
+        drop function if exists __restore_settings;
+        commit;
+    " "$database"
 }
 
-# possibly restore an existing dump in an unconfigured database, returning 0
+# possibly restore an existing dump in an unprovisioned database, returning 0
 # (true) if restored, or 1 (false) if not
 restore() {
+
     restored=false
-    if ! psql -U "$POSTGRES_USER" -c "select current_setting('app.configured')" "$database" &&
+
+    if ! psql -U "$POSTGRES_USER" -c "select current_setting('app.provisioned')" "$database" &&
         [ -f "$roles" ] &&
         [ -f "$backup" ]; then
+
         restored=true
 
         # first restore the roles (which are not included in the backup file)
-        psql -U "$POSTGRES_USER" -f "$dump.roles" "$database"
+        psql -U "$POSTGRES_USER" -f "$roles" "$database"
 
         # prevent "schema already exists" errors
         psql -U "$POSTGRES_USER" -c "drop schema if exists tiger_data cascade" "$database"
@@ -75,7 +86,9 @@ restore() {
         # restore from the backup file
         # https://postgis.net/docs/manual-dev/postgis_administration.html#hard_upgrade
         postgis_restore_pl=$(find / -name postgis_restore.pl 2>/dev/null)
-        perl "$postgis_restore_pl" "$dump.backup" |
+        echo "Restoring '$backup' using '$postgis_restore_pl';"
+        echo "errors are saved in '/restore.err'."
+        perl "$postgis_restore_pl" "$backup" |
             psql -U "$POSTGRES_USER" "$database" 2>/restore.err
         cat /restore.err
 
@@ -88,10 +101,12 @@ restore() {
         # tag the current dump files as done
         tag
     fi
+
     # this setting is used in the test above (the value doesn't matter; it just
     # needs to be set) - it's set in all cases, since if we weren't restoring a
-    # dump, we're expected to be configuring the database from DDL instead
-    psql -U "$POSTGRES_USER" -c "alter database $database set app.configured to true" "$database"
+    # dump, we're expected to be provisioning the database from DDL instead
+    psql -U "$POSTGRES_USER" -c "alter database $database set app.provisioned to true" "$database"
+
     # return true (0) or false (1)
     $restored
 }
@@ -99,6 +114,7 @@ restore() {
 # render the database read-only, before creating a new dump - restore the dump
 # in a new, empty database to get it writable again
 upgrade() {
+
     psql -U "$POSTGRES_USER" -c "
         -- temporarily disallow new connections
         -- https://www.postgresql.org/docs/13/sql-alterdatabase.html
@@ -111,10 +127,7 @@ upgrade() {
         -- terminate any (presumably writable) connections
         -- https://www.postgresql.org/docs/13/functions-admin.html
         -- https://www.postgresql.org/docs/13/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW
-        select pg_terminate_backend(pid)
-        from pg_stat_activity
-        where datname = '$database'
-        ;
+        select pg_terminate_backend(pid) from pg_stat_activity where datname = '$database';
 
         -- reallow new (read-only) connections
         alter database $database allow_connections true;
@@ -126,6 +139,6 @@ upgrade() {
     echo "NOTICE: since an 'upgrade' dump was created, database $database is now read-only" >&2
 }
 
-# dump or restore or upgrade
+# dump or restore or upgrade (see Dockerfile)
 action=$(basename "$0")
-"$action" "$@"
+$action "$@"
