postgis: refactor provisioning code

diff --git a/base/postgis/conf/dump_restore b/base/postgis/conf/dump_restore
--- a/base/postgis/conf/dump_restore
+++ b/base/postgis/conf/dump_restore
@@ -1,10 +1,7 @@
 #!/bin/bash
 
 database=$POSTGRES_DB
-if [ "$1" = '-d' ]; then
-    database=$2
-    shift 2
-fi
+[ "$1" = '-d' ] && database=$2 && shift 2
 
 dir=/fileport/$DOCKER_USER
 mkdir -p "$dir"
@@ -21,12 +18,35 @@ tag() {
     done
 }
 
+sql() {
+    local dbname=$database
+    [ "$1" = "-d" ] && dbname=$2 && shift 2
+    run() {
+        # use --no-align and --tuples-only to return an proper, unformatted
+        # value that can be used in conditional statements
+        psql -U "$POSTGRES_USER" -d "$dbname" --no-align --tuples-only "$@"
+    }
+    local input=$1
+    if [ "$input" ]; then
+        if [ -f "$input" ]; then
+            # read from given file
+            run -f "$input"
+        else
+            # execute given sql command
+            run -c "$input"
+        fi
+    else
+        # read from stdin
+        run
+    fi
+}
+
 # create a new dump, while online
 dump() {
 
     # save app.jwt_secret and any other settings passed as an argument, to get
     # set again as part of the restore
-    settings="
+    local settings="
         -- if we're upgrading, we're in default read-only mode
         start transaction read write;
 
@@ -34,8 +54,9 @@ dump() {
         create function __restore_settings()
         returns void language plpgsql as \$body\$ begin
     "
+    local value
     for setting in app.jwt_secret "$@"; do
-        value=$(psql -U "$POSTGRES_USER" -Atc "select current_setting('$setting', true)" "$database")
+        value=$(sql "select current_setting('$setting', true)")
         settings+="alter database $database set $setting to '$value';"
     done
     settings+="
@@ -44,7 +65,7 @@ dump() {
         end \$body\$;
         commit;
     "
-    psql -U "$POSTGRES_USER" -c "$settings" "$database"
+    sql "$settings"
 
     # tag any existing dump files, so that we won't overwrite them
     tag
@@ -58,55 +79,58 @@ dump() {
 
     # we don't need this in the database anymore; it just needed to be included
     # in the dump
-    psql -U "$POSTGRES_USER" -c "
+    sql "
         start transaction read write;
         drop function if exists __restore_settings;
         commit;
-    " "$database"
+    "
 }
 
 # possibly restore an existing dump in an unprovisioned database, returning 0
 # (true) if restored, or 1 (false) if not
 restore() {
 
-    restored=false
+    local restored=false
 
-    if ! psql -U "$POSTGRES_USER" -c "select current_setting('app.provisioned')" "$database" &&
-        [ -f "$roles" ] &&
-        [ -f "$backup" ]; then
-
+    do_restore() {
         restored=true
 
         # first restore the roles (which are not included in the backup file)
-        psql -U "$POSTGRES_USER" -f "$roles" "$database"
+        sql "$roles"
 
         # prevent "schema already exists" errors
-        psql -U "$POSTGRES_USER" -c "drop schema if exists tiger_data cascade" "$database"
-        psql -U "$POSTGRES_USER" -c "drop schema if exists tiger cascade" "$database"
+        sql "drop schema if exists tiger_data cascade"
+        sql "drop schema if exists tiger cascade"
 
         # restore from the backup file
         # https://postgis.net/docs/manual-dev/postgis_administration.html#hard_upgrade
+        local postgis_restore_pl
         postgis_restore_pl=$(find / -name postgis_restore.pl 2>/dev/null)
-        echo "Restoring '$backup' using '$postgis_restore_pl';"
-        echo "errors are saved in '/restore.err'."
-        perl "$postgis_restore_pl" "$backup" |
-            psql -U "$POSTGRES_USER" "$database" 2>/restore.err
+        echo "Restoring using '$postgis_restore_pl'..."
+        echo "  Saving errors in '/restore.err'..."
+        perl "$postgis_restore_pl" "$backup" | sql 2>/restore.err
+        echo "> Listing '/restore.err':"
         cat /restore.err
+        echo "< Listing '/restore.err' finished"
 
-        psql -U "$POSTGRES_USER" -Atc "select __restore_settings()" "$database"
+        sql "select __restore_settings()"
 
         # "it is wise to run ANALYZE after restoring from a dump file"
         # https://www.postgresql.org/docs/13/app-pgdump.html
-        psql -U "$POSTGRES_USER" -c "analyze" "$database"
+        sql "analyze"
 
         # tag the current dump files as done
         tag
-    fi
+    }
 
-    # this setting is used in the test above (the value doesn't matter; it just
-    # needs to be set) - it's set in all cases, since if we weren't restoring a
-    # dump, we're expected to be provisioning the database from DDL instead
-    psql -U "$POSTGRES_USER" -c "alter database $database set app.provisioned to true" "$database"
+    local provisioned
+    provisioned=$(sql "select current_setting('app.provisioned', true)")
+    [ "$provisioned" != "true" ] && [ -f "$roles" ] && [ -f "$backup" ] && do_restore
+
+    # this setting is used in the test above - it's set in all cases, since if
+    # we weren't restoring a dump, we're expected to be provisioning the
+    # database from DDL instead
+    sql "alter database $database set app.provisioned to true"
 
     # return true (0) or false (1)
     $restored
@@ -116,7 +140,8 @@ restore() {
 # in a new, empty database to get it writable again
 upgrade() {
 
-    psql -U "$POSTGRES_USER" -c "
+    # connect to NOT the database at hand
+    sql -d postgres "
         -- temporarily disallow new connections
         -- https://www.postgresql.org/docs/13/sql-alterdatabase.html
         alter database $database allow_connections false;
@@ -132,12 +157,13 @@ upgrade() {
 
         -- reallow new (read-only) connections
         alter database $database allow_connections true;
-    " postgres # connect to NOT the database at hand
+    "
 
     dump "$@"
 
     echo >&2
-    echo "NOTICE: since an 'upgrade' dump was created, database $database is now read-only" >&2
+    echo "NOTICE: since an 'upgrade' dump was created, database $database is now read-only..." >&2
+    echo "  See https://github.com/merkatorgis/docker4gis/blob/master/docs/postgis.md#upgrade..." >&2
 }
 
 # dump or restore or upgrade (see Dockerfile)
